### PR TITLE
ci: update pnpm to v8

### PR DESCRIPTION
**Pull request by FabianLars**

### CODE REVIEW

**Comment by amrbashir** [comment]
why is this needed?

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/tauri-github-bot/actions/runs/5143079569/jobs/9257649013 (via https://github.com/tauri-apps/tauri-github-bot/pull/187)

**Comment by FabianLars** [comment]
I didn't want to update pnpm to v8 in all our repos yet so i went with that for now. If you prefer to update to v8 in this repo then feel free to close this pr :)

**Comment by amrbashir** [comment]
Ah right, lets updated to v8 then.

**Pull request merged**
